{{- if and .Values.ingress.enabled .Values.service.enabled ( eq .Values.service.type "ClusterIP") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "k8s-common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
  annotations:
  {{- include "k8s-common.ingress.annotations" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ template "k8s-common.ingress.host" . }}
      http:
        paths:
          - path: "/"
            pathType: {{ .Values.ingress.pathType }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" "ssl-redirect" "servicePort" "use-annotation" "context" .) | nindent 14 }}
          - path: "/"
            pathType: {{ .Values.ingress.pathType }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" (print (include "k8s-common.ingress.serviceName" .) "-http") "servicePort" "http" "context" .) | nindent 14 }}
    {{ range .Values.ingress.extraHosts -}}
    {{- $portName := default "http" .port -}}
    - host: {{ .host | quote }}
      http:
        paths:
          {{ if .paths -}}
          {{ range .paths -}}
          - path: {{ . }}
            pathType: {{ $.Values.ingress.pathType }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" (print (include "k8s-common.ingress.serviceName" $) "-http") "servicePort" $portName "context" $) | nindent 14 }}
          {{ end -}}
          {{ else -}}
          - path: "/"
            pathType: {{ $.Values.ingress.pathType }}
            backend: {{- include "k8s-common.ingress.backend" (dict "serviceName" "ssl-redirect" "servicePort" "use-annotation" "context" $) | nindent 14 }}
          {{ end -}}
    {{ end -}}
{{- end }}
