{{- if and .Values.metrics.enabled .Values.metrics.rules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "k8s-common.names.fullname" . }}
  namespace: monitoring
  labels: {{- include "k8s-common.labels.standard" . | nindent 4 }}
spec:
  groups:
  - name: {{ include "k8s-common.names.fullname" . }}
    rules: {{ toYaml .Values.metrics.rules.spec | nindent 6 }}
{{- end }}
