{{- if .Values.rbac.create }}
{{- if .Values.serviceAccount.create -}}
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
      {{- if .Values.commonAnnotations }}
  annotations: {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "k8s-common.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-common.serviceAccount.name" . }}
{{- end }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-maintainers
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'admin'
subjects:
  - kind: Group
    name: 'aws-maintainers'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-developers
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'edit'
subjects:
  - kind: Group
    name: 'aws-developers'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-guests
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: 'aws-guests'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
{{- end }}
