{{- if and .Values.service.enabled ( eq .Values.service.type "LoadBalancer")  -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-common.ingress.serviceName" . }}-lb
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.service.annotations }}
  {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    {{- range $key, $value := default (dict) .Values.service.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $key }}
      protocol: TCP
    {{- end }}
    {{- range .Values.sidecarContainers }}
    {{- range $key, $value := default (dict) (.service).ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $key }}
      protocol: TCP
    {{- end }}
    {{- end }}
  selector: {{ include "k8s-common.labels.matchLabels" . | nindent 4 }}
{{- end }}
