---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-maintainers
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'maintainers'
subjects:
  - kind: Group
    name: 'aws-maintainers'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-developers
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'developers'
subjects:
  - kind: Group
    name: 'aws-developers'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-sre
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'support'
subjects:
  - kind: Group
    name: 'aws-support'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-qa
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'qa'
subjects:
  - kind: Group
    name: 'aws-qa'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-business
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'qa'
subjects:
  - kind: Group
    name: 'aws-business'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-aws-guests
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'qa'
subjects:
  - kind: Group
    name: 'aws-guests'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
{{- if .Values.githubActionsIntegration }}
---
apiVersion: {{ include "k8s-common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "k8s-common.names.fullname" . }}-github
  namespace: {{ include "k8s-common.names.namespace" . | quote }}
  labels: {{- include "k8s-common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "k8s-common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: 'github'
    namespace: {{ include "k8s-common.names.namespace" . | quote }}
{{- end }}
