{{- if .Values.autoscaling.enabled -}}
apiVersion: {{ include "k8s-common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "k8s-common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "k8s-common.labels.standard" . | nindent 4 }}
spec:
  {{- if .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.behavior | nindent 4 }}
  {{- end }}
  scaleTargetRef:
    {{ if .Values.rollouts.enabled -}}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{ else -}}
    apiVersion: {{ include "k8s-common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    {{ end -}}
    name: {{ include "k8s-common.names.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics: {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
{{- end }}
